# Generated by Django 4.0.2 on 2022-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
